### ISSUE TITLE
about sonarqube metric value type

### ISSUE THREAD

**Issue by identifysun** [multiservicio/sonarqube-exporter#1]
Sonarqube default have many datatype:

for example

`{
  "types": [
    "INT",
    "FLOAT",
    "PERCENT",
    "BOOL",
    "STRING",
    "MILLISEC",
    "DATA",
    "LEVEL",
    "DISTRIB",
    "RATING",
    "WORK_DUR"
  ]`

I see you code and not convert metric datatype,
I want to know how you do it.

finally，Can you provide a grafana dashboard templates.

thx.

**Comment by poyarkov111** [comment]
+1 Can you provide a grafana dashboard template?

**Comment by aloneboat** [comment]
+1 Can you provide a grafana dashboard template?
